"""add description column to observation

Revision ID: 354bd4507022
Revises: ac4cb1319bfe
Create Date: 2017-09-28 11:21:46.229733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354bd4507022'
down_revision = 'ac4cb1319bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observations', 'description')
    # ### end Alembic commands ###
