"""empty message

Revision ID: 481b82969ded
Revises: 
Create Date: 2018-03-22 08:58:48.430147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481b82969ded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acquisitions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisitions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('params', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name='acquisitions_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='acquisitions_pkey')
    )
    # ### end Alembic commands ###
