"""empty message

Revision ID: b1e41efee6b8
Revises: e0e07365ced4
Create Date: 2018-03-20 12:34:15.153234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e41efee6b8'
down_revision = 'e0e07365ced4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acquisitions', 'params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisitions', sa.Column('params', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
